apiVersion: apps/v1
kind: Deployment
metadata:
  name: group-3-deployment-netflix-clone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix-clone
  template:
    metadata:
      labels:
        app: netflix-clone
    spec:
      containers:
      - name: netflix-clone
        image: YOUR_ECR_URL/group-3-ecr-netflix-clone:latest
        ports:
        - containerPort: 5000
        env:
        - name: TMDB_API_KEY
          valueFrom:
            secretKeyRef:
              name: tmdb-api-key-secret
              key: TMDB_API_KEY
